Fix typing error TS1046
When using DetectRTC with Typescript 3.9.7, the typings caused an error
(TS1046). Since TS 0.9, top level non-interface definitions need to use
the "declare" keyword.